name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1
          kubectl wait pods --for condition=Ready --timeout=90s --all
      - name: Test Deployment
        run: |
          kubectl port-forward deployment/kubernetes-bootcamp 8001:80 &
          sleep 3
          kubectl get deployments
          curl http://localhost:8001/version
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
