name: "Create cluster using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Testing
        run: |
          kubectl wait nodes --for condition=Ready --all
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
      - name: Deploy Application
        run: |
          kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1
          kubectl wait pods --for condition=Ready --timeout=90s --all
          kubectl expose deployment/kubernetes-bootcamp --type=NodePort --port 8080
      #- name: Setup Kubernetes port-forward daemon
      #  uses: vbem/k8s-port-forward@v1
      #  with:
      #    workload: 'deployment/kubernetes-bootcamp'
      - name: Test Deployment
        run: |
          kubectl get deployments
          sleep 3
          curl http://localhost:8080/version
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cd
